#!/usr/bin/bash
if (( $# != 0 ));then
    if [[ -d  $1 ]];then
            rm -r $1
        elif [[ -f $1 ]];then
            echo "Not exist"        
    fi
else
    echo "please enter a valid databse table to remove"
fi